#ifndef __VERSION_H
#define __VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 3
#define VERSION_BUILD_ID "20121215-212201"
#define PRODUCT_NAME "RS485 IEC METER TEST"


#endif /* end __VERSION_H */
